server:
  port: ${HTTP_PORT:8082}

spring:
  application:
    name: service-b

logging:
  level:
    org.apache.dubbo: ${LOG_LEVEL:INFO}
    com.example.demo: ${LOG_LEVEL:INFO}
    org.apache.dubbo.rpc.protocol.tri: ${LOG_LEVEL:INFO}
    org.apache.dubbo.registry: ${LOG_LEVEL:INFO}
    io.grpc: ${LOG_LEVEL:INFO}

dubbo:
  application:
    name: service-b
    metadataServicePort: ${DUBBO_PORT:20882}
    metadataType: remote
    service-discovery:
      migration: FORCE_APPLICATION
  protocol:
    name: tri
    port: ${DUBBO_PORT:20882}
  registry:
    address: nacos://${NACOS_ADDR:127.0.0.1:8848}
    register-mode: instance
  metadata-report:
    address: nacos://${NACOS_ADDR:127.0.0.1:8848}
  scan:
    base-packages: com.example.demo.serviceb.dubbo
