apiVersion: v1
kind: Service
metadata:
  name: service-c
  namespace: demo
spec:
  selector:
    app: service-c
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  - name: grpc
    port: 9093
    targetPort: 9093
