apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: demo
spec:
  selector:
    app: service-a
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: grpc
    port: 9091
    targetPort: 9091
