apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: demo
spec:
  selector:
    app: service-b
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  - name: grpc
    port: 9092
    targetPort: 9092
