server:
  port: ${HTTP_PORT:8083}

spring:
  application:
    name: service-c

dubbo:
  application:
    name: service-c
    metadataServicePort: ${DUBBO_PORT:20883}
  protocol:
    name: tri
    port: ${DUBBO_PORT:20883}
  registry:
    address: nacos://${NACOS_ADDR:127.0.0.1:8848}
  scan:
    base-packages: com.example.demo.servicec.dubbo
