server:
  port: ${HTTP_PORT:8081}

spring:
  application:
    name: service-a
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        metadata:
          unit: ${ROUTING_UNIT:}
          idc: ${ROUTING_IDC:}
          user: ${ROUTING_USER:}
    compatibility-verifier:
      enabled: false

grpc:
  server:
    port: ${GRPC_PORT:9091}
  client:
    service-b:
      address: discovery:///service-b
      negotiation-type: plaintext
