server:
  port: ${HTTP_PORT:8081}

spring:
  application:
    name: service-a

dubbo:
  application:
    name: service-a
    metadata-type: local
    register-mode: interface
  protocol:
    name: dubbo
    port: ${DUBBO_PORT:20881}
  registry:
    address: nacos://${NACOS_ADDR:127.0.0.1:8848}
    register-mode: interface
    parameters:
      unit: ${ROUTING_UNIT:}
      idc: ${ROUTING_IDC:}
  scan:
    base-packages: com.example.demo.servicea.dubbo
